import { Pressable, StyleSheet, Text, View } from 'react-native';

import { theme, useThemeColors } from '@/lib/theme';
import { useToast } from '@/lib/toast';

/**
 * The app's one logo mark — a bold "SL" on an accent-colored square. Used on
 * sign-in/sign-up (via AuthLogo below) and anywhere else in the app that
 * needs the logo (onboarding, premium). The static icon/splash-screen/
 * favicon image assets (assets/icon.png etc., generated by
 * scratch/gen-assets.js) are the same mark baked to PNG, since native app
 * icons can't render a live component.
 */
export function AppMark({ size = 46 }: { size?: number }) {
  const colors = useThemeColors();
  return (
    <View
      style={[
        styles.mark,
        { width: size, height: size, borderRadius: size * (theme.radius.sm / 46), backgroundColor: colors.accent },
      ]}
    >
      <Text style={[styles.markText, { fontSize: size * (26 / 46) }]}>SL</Text>
    </View>
  );
}

/** The "SL / Step League" logo block shared by sign-in and sign-up (design screen 2a). */
export function AuthLogo({ tagline }: { tagline: string }) {
  const colors = useThemeColors();
  return (
    <View style={{ gap: theme.space(6.5) }}>
      <View style={{ flexDirection: 'row', alignItems: 'center', gap: theme.space(3.25) }}>
        <AppMark />
        <Text style={[styles.wordmark, { color: colors.text }]}>{'Step\nLeague'}</Text>
      </View>
      <Text style={[styles.tagline, { color: colors.textSubtle }]}>{tagline}</Text>
    </View>
  );
}

/**
 * Apple/Google sign-in, styled to match the design — not wired to real
 * OAuth. Real Apple/Google sign-in needs credentials (Apple Developer team,
 * Google Cloud OAuth client) only the app's owner can create, so these stay
 * placeholders until that's set up.
 */
export function SocialButtons() {
  const colors = useThemeColors();
  const { showToast } = useToast();
  function comingSoon(provider: string) {
    showToast(`${provider} sign-in is coming soon — use email for now.`);
  }
  return (
    <View style={{ gap: theme.space(2.5) }}>
      <View style={styles.dividerRow}>
        <View style={[styles.dividerLine, { backgroundColor: colors.borderStrong }]} />
        <Text style={[styles.dividerText, { color: colors.textDim }]}>OR</Text>
        <View style={[styles.dividerLine, { backgroundColor: colors.borderStrong }]} />
      </View>
      <Pressable onPress={() => comingSoon('Apple')} style={[styles.socialButton, { borderColor: colors.controlBorder }]}>
        <Text style={[styles.socialButtonText, { color: colors.text }]}>Continue with Apple</Text>
      </Pressable>
      <Pressable onPress={() => comingSoon('Google')} style={[styles.socialButton, { borderColor: colors.controlBorder }]}>
        <Text style={[styles.socialButtonText, { color: colors.text }]}>Continue with Google</Text>
      </Pressable>
    </View>
  );
}

const styles = StyleSheet.create({
  mark: {
    width: 46,
    height: 46,
    borderRadius: theme.radius.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  markText: {
    color: '#0b0c0a',
    fontSize: 26,
    fontFamily: theme.fontFamily.heading,
    letterSpacing: -0.5,
  },
  wordmark: {
    fontSize: 34,
    lineHeight: 31,
    fontFamily: theme.fontFamily.heading,
    letterSpacing: 0.3,
    textTransform: 'uppercase',
  },
  tagline: {
    fontSize: 15,
    lineHeight: 22,
    maxWidth: 290,
    fontFamily: theme.fontFamily.bodyMedium,
  },
  dividerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.space(3),
    paddingVertical: theme.space(1),
  },
  dividerLine: {
    flex: 1,
    height: 1,
  },
  dividerText: {
    fontSize: 9,
    fontFamily: theme.fontFamily.bodySemiBold,
    letterSpacing: 1.8,
  },
  socialButton: {
    borderWidth: theme.border,
    borderRadius: theme.radius.sm,
    paddingVertical: theme.space(3.75),
    alignItems: 'center',
  },
  socialButtonText: {
    fontSize: 12,
    fontFamily: theme.fontFamily.bodySemiBold,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
});
